name: Commit subject
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check-commit
        uses: docker://ghcr.io/haproxytech/commit-check:3.0.0
        env:
          API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
